name = "proglianote"
compatibility_date = "2024-11-01"

# ビルド後のファイル（distフォルダ）を配信する設定
[assets]
directory = "./dist"
binding = "ASSETS"

# すべてのパスを index.html に向ける（Reactのルーティング用）
[[routes]]
pattern = "/*"
zone_name = ""
